### PR TITLE
Initial Upload Of Files

### PR DESCRIPTION
**Pull request by delateurj**

### CODE REVIEW

**Comment by NicholasDeLateur** [comment]
I'm a little concerned about having a master with multiple working mains; the fact that I have multiple myself is something I'm supposed to be taking care of. If I merged these it will only be adding to it. Not sure where to go from here, doesn't really make sense for us to be working on separate copies that share a master repo does it?

**Comment by NicholasDeLateur** [comment]
Out of curiosity I've changed the master branch trivially just to check how it deals with that.

**Comment by delateurj** [comment]
I agree we need to do some clean up of the repo and decide on approach.
Perhaps a skype session this weekend?

On Thu, May 26, 2016 at 3:24 PM, Nicholas DeLateur <notifications@github.com

**Comment by NicholasDeLateur** [comment]
Yeah, I'll email you.

**Pull request merged**
